# Generated by Django 2.0.3 on 2018-06-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecobrick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardName', models.CharField(max_length=250)),
                ('pointCost', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='rewards',
        ),
        migrations.AddField(
            model_name='myreward',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecobrick.UserDetail'),
        ),
    ]
