# Generated by Django 2.0.3 on 2018-06-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecobrick', '0003_auto_20180630_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='brickPoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
