# Generated by Django 2.0.3 on 2018-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecobrick', '0005_userdetail_ispremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
